export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-neutral dark:prose-invert space-y-6">
        <p><strong>Last updated:</strong> March 2026</p>

        <h2 className="text-xl font-semibold mt-6">1. Acceptance of Terms</h2>
        <p>
          By accessing or using Codepylot, you agree to be bound by these Terms of Service. If you do not agree, do
          not use the service.
        </p>

        <h2 className="text-xl font-semibold mt-6">2. Description of Service</h2>
        <p>
          Codepylot is an AI-powered sprint board for managing software development projects. Features include
          project management, story tracking, AI-assisted story writing, and agent-based code implementation.
        </p>

        <h2 className="text-xl font-semibold mt-6">3. Accounts</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>You must provide accurate information when creating an account</li>
          <li>You are responsible for maintaining the security of your account</li>
          <li>You must be at least 18 years old to use the service</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6">4. Subscriptions & Billing</h2>
        <ul className="list-disc pl-6 space-y-1">
          <li>Free accounts have limited features (3 projects, 50 stories per project)</li>
          <li>Pro subscriptions are billed monthly and can be canceled at any time</li>
          <li>Cancellation takes effect at the end of the current billing period</li>
          <li>No refunds for partial months</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6">5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1">
          <li>Use the service for illegal purposes</li>
          <li>Attempt to gain unauthorized access to the service</li>
          <li>Interfere with the proper operation of the service</li>
          <li>Reverse engineer or attempt to extract source code</li>
        </ul>

        <h2 className="text-xl font-semibold mt-6">6. Intellectual Property</h2>
        <p>
          You retain ownership of all content you create using Codepylot. We do not claim ownership of your
          projects, stories, or code generated by agents on your behalf.
        </p>

        <h2 className="text-xl font-semibold mt-6">7. Limitation of Liability</h2>
        <p>
          Codepylot is provided &quot;as is&quot; without warranty of any kind. We are not liable for any damages arising
          from the use of the service, including but not limited to code generated by AI agents.
        </p>

        <h2 className="text-xl font-semibold mt-6">8. Changes to Terms</h2>
        <p>
          We may update these terms at any time. Continued use of the service after changes constitutes acceptance
          of the new terms.
        </p>

        <h2 className="text-xl font-semibold mt-6">9. Contact</h2>
        <p>For questions about these terms, contact us at legal@codepylot.dev.</p>
      </div>
    </div>
  );
}
