apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codepylot
  namespace: codepylot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - codepylot.aydex.nl
      secretName: codepylot-tls
  rules:
    - host: codepylot.aydex.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codepylot
                port:
                  number: 80
