apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "codepylot.fullname" . }}-repos
  labels:
    {{- include "codepylot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.persistence.repos.storageClass }}
  storageClassName: {{ .Values.persistence.repos.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.repos.size }}
