apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codepylot.fullname" . }}-secret
  labels:
    {{- include "codepylot.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ include "codepylot.databaseUrl" . | b64enc | quote }}
  AUTH_SECRET: {{ .Values.env.AUTH_SECRET | b64enc | quote }}
  ENCRYPTION_KEY: {{ .Values.env.ENCRYPTION_KEY | b64enc | quote }}
  CRON_SECRET: {{ .Values.env.CRON_SECRET | b64enc | quote }}
  {{- if .Values.env.GITHUB_ID }}
  GITHUB_ID: {{ .Values.env.GITHUB_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.GITHUB_SECRET }}
  GITHUB_SECRET: {{ .Values.env.GITHUB_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.GOOGLE_ID }}
  GOOGLE_ID: {{ .Values.env.GOOGLE_ID | b64enc | quote }}
  {{- end }}
  {{- if .Values.env.GOOGLE_SECRET }}
  GOOGLE_SECRET: {{ .Values.env.GOOGLE_SECRET | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | b64enc | quote }}
  POSTGRES_DB: {{ .Values.postgresql.auth.database | b64enc | quote }}
  {{- end }}
